name: Waka Readme

on:
  workflow_dispatch:
  schedule:
  - cron: "0 */6 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Update README
        uses: athul/waka-readme@v0.3.0
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: all_time
          LANG_COUNT: 5
          SHOW_TOTAL: true
          SHOW_TIME: true
          SHOW_TITLE: true
          BLOCKS: ░▒▓█
          COMMIT_MESSAGE: "Updated WakaTime stats"
